---
- hosts: iris-dbserver
  roles:
    - iris-db

- hosts: iris-webservers
  sudo: yes
  roles:
    - { role: install-apache-mod, module_name: wsgi }
    - { role: apache-mod, module_name: wsgi }
    - iris-web
