---
- group: name={{sys_group}} system=yes

- user: name={{sys_user}} group={{sys_group}} home={{sys_user_home}} system=yes

- name: make require pathes
  file: path="{{item}}" owner={{sys_user}} group={{sys_group}} state=directory
  with_items:
    - "{{static_root}}"
    - "{{media_root}}"
    - "{{log_path}}"
    - "{{etc_path}}"

- zypper: state=present name="{{item}}"
  with_items:
    - python-pip
    - python-devel
    - openldap2-devel
    - cyrus-sasl-devel
    - libopenssl-devel
    - libxml2-devel
    - libxslt-devel

- name: Install IRIS packages
  pip: name={{iris_package}}
  notify: restart apache

- template: src=iris.conf.j2 dest=/etc/iris/iris.conf
    owner=iris group=iris
  notify: restart apache

# this will never report 'changed' status
- name: Find IRIS path
  command: python -c "import os; from iris import manage; print(os.path.dirname(manage.__file__))"
  register: iris_path
  changed_when: False

- django_manage: command="{{item}}" app_path="{{iris_path.stdout}}"
  with_items:
    - collectstatic
    - syncdb
    - migrate

- name: Create django cache table
  django_manage: command=createcachetable cache_table={{cache_table}} app_path="{{iris_path.stdout}}"

- copy: src=wsgi.py dest={{iris_root}}/wsgi.py

- template: src=apache.conf.j2 dest=/etc/apache2/vhosts.d/iris.conf
  notify: restart apache

- template: src=listen.conf.j2 dest=/etc/apache2/listen.conf
     mode=0644 owner=root group=root
  notify: restart apache

- cron: name="update iris data" user="{{sys_user}}" hour="10,14" minute="0" job="/usr/bin/update_iris_data.sh >> {{log_path}}/iris_update.log 2>&1"
